@startuml
package {
        usecase "<b>UC_5</b>\nПрацювати з наборами даних" as UC_5 #aaeeaa
    }
    
    usecase "<b>UC_5.1</b>\nДодати дані" as UC_5.1
    usecase "<b>UC_5.2</b>\nОновити дані" as UC_5.2

    UC_5.1 .u.> UC_5 : extends
    UC_5.2 .u.> UC_5 : extends

    Модератор -> UC_5

@enduml
