@startuml
package {
        usecase "<b>UC_2</b>\nПрацювати з наборами даних" as UC_2 #aaeeaa
    }
    
    usecase "<b>UC_2.1</b>\nДодати дані" as UC_2.1
    usecase "<b>UC_2.2</b>\nОновити дані" as UC_2.2

    UC_2.1 .u.> UC_2 : extends
    UC_2.2 .u.> UC_2 : extends

    Модератор -> UC_2

@enduml
