@startuml

    |Адміністратор|
    start
    :Переходить до особистого кабінету;
    |Адміністратор|
    :Натискає кнопку "Звіти";
    |Система|
    :Відображає сторінку зі списком \nвсіх звітів, відсортованих за \nдатою додавання;
    |Адміністратор|
    :Вибирає звіт;
    |Система|
    :Система відображує звіт.;
        |Адміністратор|
    stop;
@enduml
