@startuml
    |Користувач|
    start
    :Натискає кнопку "Завантажити";
    |Система|
    :Надає форму для вибору \nдиректорії для збереження.;
    |Користувач|
    :Налаштовує шлях до директорії;
    |Система|
    :Завантажує дані у вибрану \nкористувачем директорію.;
        |Користувач|
    stop;
@enduml
