@startuml
    |Користувач|
    start
    :Натискає кнопку "Завантажити";
    |Система|
    :Запитує вибрати директорію для збереження.;
    |Користувач|
    :Налаштовує шлях до директорії;
    |Система|
    :Завантажує дані у вибрану \nкористувачем директорію.;
        |Користувач|
    end;
@enduml
