@startuml

    |Користувач|
    start
    :Натискає кнопку "Залишити коментар";
    |Система|
    :Надає форму для вводу коментара;
    |Користувач|
    :Вводить коментар;
    |Користувач|
    :Натискає кнопку "Відправити";
    |Система|
    :Прив'язує введений користувачем коментар до набору даних;
        |Користувач|
    end;
@enduml
