@startuml

    |Користувач|
    start
    :Натискає кнопку "Залишити коментар";
    |Система|
    :Відображає вікно для вводу;
    |Користувач|
    :Вводить коментар;
    |Користувач|
    :Натискає кнопку "Відправити";
    |Система|
    :Прив'язує введений користувачем коментар до набору даних;
        |Користувач|
    end;
@enduml
