@startuml
    |Менеджер|
    start
    :Натискає кнопку "Завантажити масив даних";
    |Система|
    :Запитує вибрати спосіб завантаження;
    |Менеджер|
    :Вибирає спосіб завантаження;
    |Система|
    :Надає форму для заповнення;
    |Менеджер|
    :Заповнює та натискає кнопку "Відправити";
    |Система|
    :Додає новий масив даних до системи;
        |Менеджер|
    end;
@enduml
