@startuml
    |Менеджер|
    start
    :Натискає кнопку \n"Завантажити масив даних";
    |Система|
    :Запитує вибрати спосіб \nзавантаження(таблиця, стаття);
    |Менеджер|
    :Вибирає спосіб завантаження;
    |Система|
    :Надає форму для вибору \nфайлу для завантаження;
    |Менеджер|
    :Заповнює та натискає кнопку "Відправити";
    |Система|
    :Додає новий масив даних до системи;
        |Менеджер|
    end;
@enduml
