@startuml
    |Менеджер|
    start
    :Натискає кнопку "Внести зміни";
    |Система|
    :Надає форму для заповнення;
    |Менеджер|
    :Заповнює та натискає кнопку "Відправити";
    |Система|
    :Оновлює дані у базі.;
        |Менеджер|
    stop;
@enduml
