@startuml

    |Менеджер|
    start
    :Натискає кнопку "Відповісти";
    |Система|
    :Надає форму для заповнення;
    |Менеджер|
    :Заповнює та натискає кнопку "Відправити";
    |Система|
    :Прикріпляє відповідь до набору даних.;
        |Менеджер|
    stop;
@enduml
