@startuml

    |Менеджер|
    start
    :Натискає кнопку "Оформити звіт";
    |Система|
    :Надає форму для заповнення(джерела, \nвикористані ресурси, особистий коментар);
    |Менеджер|
    :Заповнює та натискає кнопку "Відправити";
    |Система|
    :Прикріпляє звіт до набору даних;
        |Менеджер|
    stop;
@enduml
