@startuml

    |Адміністратор|
    start
    :Переходить до особистого кабінету;
    |Адміністратор|
    :Натискає кнопку "Налаштування доступу";
    |Система|
    :Відображає сторінку зі списком \nвсіх користувачів та модераторів;
    |Адміністратор|
    :Вибирає користувача та змінює його права(Модератор, Користувач);
    |Система|
    :Вносить зміни до налаштування доступу;    
    |Адміністратор|
    stop;
@enduml
