@startuml

    |Адміністратор|
    start
    :Переходить до особистого кабінету;
    |Адміністратор|
    :Натискає кнопку "Налаштування доступу";
    |Система|
    :Відображає сторінку зі списком \nвсіх користувачів та модераторів;
    |Адміністратор|
    :Вибирає користувача та натискає \nкнопку "Надати права Модератора";
    |Система|
    :Надає користувачу права модератора;    
    |Адміністратор|
    end;
@enduml
