@startuml

|Користувач|
    |Користувач|
    start
    :Натискає кнопку "Вхід";
    |Система|
    :Перенаправляє Користувача на сторінку входу;    
    :Надає форму для вводу імені та паролю;  
    |Користувач|
    :Вводить необхідні дані;  
    |Система|
    :Аналізує введені дані;  
    :Перенаправляє на сторінку особистого кабінету;
        |Користувач|
    end;
@enduml
