@startuml

|Користувач|
        start
        : Натискає кнопку "Зареєструватися";
    |Система|
        : Надає форму реєстрації;
    |Користувач|
        :Користувач заповнює поля:\n ім'я, вік, електронна пошта;
        :Натискає кнопку "Відправити";
    |Система|
        : Аналізує надані дані;
        : Вносить надані дані у \n загальну базу даних;
        : Перенаправляє в особистий кабінет;
    |Користувач|
        stop;
@enduml
