@startuml

|Користувач|
        start
        : Натискає кнопку "Зареєструватися";
    |Система|
        : Надає форму реєстрації;
    |Користувач|
        :Заповнює форму і\nнатискає кнопку "Відправити";
        :Виставляє додаткові налаштування;
    |Система|
        : Аналізує надані дані;
        : Перенаправляє в особистий кабінет;
    |Користувач|
        stop;
@enduml
