@startuml

|Користувач|
        start
        : Натискає кнопку "Додаткові інструменти";
    |Система|
        : Відображає вікно з вибором інструментів(таблиці, графіки, діаграми);
    |Користувач|
        :Вибирає з заданого переліку необхідні \nінструменти обробки даних;
    |Система|
        :Надає можливість внести корективи(додати інший набір даних, порівняти);
    |Користувач|
        :Виставляє додаткові налаштування;
    |Система|
        : Система відображає дані в інтерактивному виді;
    |Користувач|
        stop;
@enduml
