@startuml

|Користувач|
    start
    :Вводить ключові слова для пошуку;
    |Система|
    :Здійснює запит у базу даних;
    |Система|
    :Система відображає знайдену \nінформацію у базі даних;
    |Користувач|
    stop;
@enduml


