@startuml

|Користувач|
        start
        : Натискає кнопку "Додаткові інструменти";
    |Система|
        : Відображає вікно з вибором інструментів;
    |Користувач|
        :Вибирає з заданого переліку необхідні \nінструменти обробки даних;
        :Виставляє додаткові налаштування;
    |Система|
        : Система відображає дані в інтерактивному виді;
    |Користувач|
        :
        end
@enduml
