@startuml
left header
        <font color=000 size=16><b>ID:</b> UC_3
        <font color=000 size=16><b>Назва:</b> Завантажувати дані.
        <font color=000 size=16><b>Учасники:</b> Користувач, Система.
        <font color=000 size=16><b>Передумови:</b> UC_2.1, можливо UC_2.2.
        <font color=000 size=16><b>Результат:</b> Дані завантажені на носії Користувача.
        <font color=000 size=16><b>Виключні ситуації:</b> Відсутні
        
        <font color=000 size=16><b>Основний сценарій:</b>
        
    end header

    |Користувач|
    start
    :Натискає кнопку "Завантажити";
    |Система|
    :Запитує вибрати директорію для збереження.;
    |Користувач|
    :Налаштовує шлях до директорії;
    |Система|
    :Завантажує дані у вибрану \nкористувачем директорію.;
        |Користувач|
    end;
@enduml
